#ifndef BASE_ALLOCATOR_FEATURES_H_
#define BASE_ALLOCATOR_FEATURES_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_EXPERIMENTAL_ALLOCATOR_SHIM() (0)
#define BUILDFLAG_INTERNAL_ENABLE_WIN_ALLOCATOR_SHIM_TESTS() (0)

#endif
